#' Rotated Multivariate Linear Mixed Model (RmvLMM) for multi-trait GWAS
#'
#' @description Performs multi-trait association testing using the RmvLMM framework. 
#' Note: RmvLMM assumes the phenotype matrix Y contains quantitative (continuous) traits.
#'
#' @param Y Numeric matrix of phenotypes (N individuals x D traits).
#' @param X Numeric matrix of covariates (N individuals x C covariates). Must include a column of 1s.
#' @param K Numeric matrix for Kinship (N x N). Provide either K or K_precomp.
#' @param K_precomp A list containing pre-computed eigenvalue decomposition of K (`$Ak_diag, vector of eigenvalues` and `$Qk, left eigenvectors matrix`). 
#' @param G Numeric matrix of genotypes (M SNPs x N individuals) or a numeric vector for a single SNP.
#' @param out_file Optional. Character string specifying the output .rds file path.
#' @param max_iter Integer. Maximum iterations for MoM-REML. Default is 200.
#'
#' @return A list containing the SNP association results (`results`: data.frame) and variance components (`Vb`, `Ve`).
#' @export
run_RmvLMM <- function(Y, X, K = NULL, K_precomp = NULL, G, out_file = NULL, max_iter = 200) {
  
  if (any(is.na(Y)) || any(is.na(X)) || any(is.na(G))) {
    stop("Error: Y, X, and G matrices must not contain NA values.")
  }
  
  n <- nrow(Y)
  if (nrow(X) != n) stop("Error: Rows in Y and X must be identical.")
  
  if (is.vector(G)) {
    G <- matrix(G, nrow = 1, ncol = n)
    rownames(G) <- "Target_SNP"
  }
  if (ncol(G) != n) stop("Error: Columns in G must match rows in Y.")
  if (is.null(rownames(G))) stop("Error: Genotype matrix G must have row names for SNP IDs.")
  
  if (is.null(K) && is.null(K_precomp)) {
    stop("Error: You must provide either K or K_precomp.")
  }
  
  precomputed_data <- prepare_lmm_precomputation(K = K, X = X, Y = Y, K_precomp = K_precomp)
  results <- fit_multivariate_lmm_optimized(precomputed_data, max_iter = max_iter, tol = 1e-4, verbose = 0)
  test_data <- prepare_hypothesis_test_data(precomputed_data, Vb_est = results$Vb, Ve_est = results$Ve)
  
  Qk_t <- t(precomputed_data$Qk)
  G_rot <- tcrossprod(Qk_t, G) 
  
  p_value_vector <- calculate_p_values_for_matrix_detailed(
    test_data = test_data, 
    G_rot = G_rot,
    comb_method = "Top2", 
    mode = "single"
  )
  
  df_res <- data.frame(
    SNP = rownames(G),
    p_TOP2 = as.numeric(p_value_vector),
    stringsAsFactors = FALSE
  )
  
  final_obj <- list(
    results = df_res,
    Vb = round(results$Vb, 5),
    Ve = round(results$Ve, 5)
  )
  
  if (!is.null(out_file)) {
    saveRDS(final_obj, file = out_file)
  }
  return(final_obj)
}


#' Aggregate Group-wise RmvLMM Results using Divide-and-combine strategy
#'
#' @description Reads multiple .rds files generated by `run_RmvLMM`, performs Fisher's omnibus 
#' combination, and calibrates P-values using a Generalized Gamma distribution based on independent SNPs.
#'
#' @param rds_files A character vector of file paths to the .rds files generated by `run_RmvLMM`.
#' @param indep_snp_file File path to the list of approximately independent SNPs. The file must contain a column named 'SNP'.
#' @param out_file Optional. File path to save the final calibrated results (.rds).
#'
#' @return A list containing the calibrated P-value data.frame and averaged variance components (Vb, Ve).
#' @export
bank_RmvLMM <- function(rds_files, indep_snp_file, out_file = NULL) {
  
  if (!requireNamespace("data.table", quietly = TRUE)) stop("Package 'data.table' is required.")
  
  indep_dt <- data.table::fread(indep_snp_file)
  if (!"SNP" %in% colnames(indep_dt)) stop("Error: The independent SNP file must contain a 'SNP' column.")
  indep_snps <- as.character(indep_dt$SNP)
  
  first_obj <- readRDS(rds_files[1])
  base_dt <- data.table::as.data.table(first_obj$results[, c("SNP", "p_TOP2")])
  data.table::setnames(base_dt, "p_TOP2", "Part1")
  
  n_snps <- nrow(base_dt)
  base_snps <- base_dt$SNP
  
  Vb_sum <- first_obj$Vb
  Ve_sum <- first_obj$Ve
  
  for (i in 2:length(rds_files)) {
    tmp_obj <- readRDS(rds_files[i])
    tmp_res <- tmp_obj$results
    
    if (nrow(tmp_res) != n_snps || !all(tmp_res$SNP == base_snps)) {
      stop(sprintf("Error: SNP IDs or their order in %s do not exactly match the first file.", rds_files[i]))
    }
    
    data.table::set(base_dt, j = paste0("Part", i), value = tmp_res$p_TOP2)
    
    Vb_sum <- Vb_sum + tmp_obj$Vb
    Ve_sum <- Ve_sum + tmp_obj$Ve
  }
  
  part_cols <- paste0("Part", 1:length(rds_files))
  
  base_dt[, internal_T := apply(.SD, 1, function(pvec) {
    pvec[pvec < 1e-150] <- 1e-150 
    -2 * sum(log(pvec), na.rm = TRUE)
  }), .SDcols = part_cols]
  
  base_dt[, (part_cols) := NULL]
  
  T_indep <- base_dt[SNP %in% indep_snps, internal_T]
  lower_bound <- quantile(T_indep, 0.005, na.rm = TRUE)
  upper_bound <- quantile(T_indep, 0.995, na.rm = TRUE)
  T_indep_final <- T_indep[T_indep >= lower_bound & T_indep <= upper_bound]
  
  if (length(T_indep_final) < 100) {
    stop("Error: Too few valid independent SNPs (< 100) found after trimming. Check your SNP list mapping.")
  }
  
  est_gg <- fit.generalgamma.mle(T_indep_final)
  
  base_dt[, p_omnibus := flexsurv::pgengamma(q = internal_T, 
                                             mu = as.numeric(est_gg["mu"]), 
                                             sigma = as.numeric(est_gg["sigma"]), 
                                             Q = as.numeric(est_gg["Q"]), 
                                             lower.tail = FALSE)]
  base_dt[, internal_T := NULL]
  
  final_res_obj <- list(
    results = as.data.frame(base_dt),
    Vb = round(Vb_sum / length(rds_files), 5),
    Ve = round(Ve_sum / length(rds_files), 5)
  )
  
  if (!is.null(out_file)) {
    saveRDS(final_res_obj, out_file)
  }
  return(final_res_obj)
}